MOCK_AGENCY = {
    "id":    "aaaaaaaa-0000-0000-0000-000000000001",
    "name":  "Agencija Prima",
    "email": "vlasnik@primakretnine.rs",
}

MOCK_LISTINGS = [
    {
        "id":           "11111111-0000-0000-0000-000000000001",
        "agency_id":    "aaaaaaaa-0000-0000-0000-000000000001",
        "ref_number":   "PRI-001",
        "type":         "stan",
        "transaction":  "prodaja",
        "title":        "Svetao dvosoban stan na Vracaru",
        "description":  "Odlican dvosoban stan u mirnoj ulici, visoko prizemlje, nedavno renoviran.",
        "price":        145000,
        "currency":     "EUR",
        "area_m2":      58,
        "city":         "Beograd",
        "municipality": "Vracar",
        "street":       "Cara Nikolaja II 14",
        "floor":        3,
        "total_floors": 6,
        "rooms":        2,
        "year_built":   1985,
        "heating":      "centralno",
        "parking":      False,
        "elevator":     True,
        "furnished":    "namesteno",
        "images":       ["https://placehold.co/800x600?text=Stan+1",
                         "https://placehold.co/800x600?text=Stan+2"],
        "active":       True,
    },
    {
        "id":           "11111111-0000-0000-0000-000000000002",
        "agency_id":    "aaaaaaaa-0000-0000-0000-000000000001",
        "ref_number":   "PRI-002",
        "type":         "stan",
        "transaction":  "zakup",
        "title":        "Trosoban stan Novi Beograd blok 45",
        "description":  "Prostran trosoban stan sa garage mestom. Useljivost odmah.",
        "price":        900,
        "currency":     "EUR",
        "area_m2":      78,
        "city":         "Beograd",
        "municipality": "Novi Beograd",
        "street":       "Jurija Gagarina 22",
        "floor":        7,
        "total_floors": 12,
        "rooms":        3,
        "year_built":   1978,
        "heating":      "centralno",
        "parking":      True,
        "elevator":     True,
        "furnished":    "namesteno",
        "images":       ["https://placehold.co/800x600?text=Stan+NB"],
        "active":       True,
    },
    {
        "id":           "11111111-0000-0000-0000-000000000003",
        "agency_id":    "aaaaaaaa-0000-0000-0000-000000000001",
        "ref_number":   "PRI-003",
        "type":         "kuca",
        "transaction":  "prodaja",
        "title":        "Porodicna kuca sa placem — Zemun",
        "description":  "Kuca P+1 na placu od 400m2. Dva zasebna ulaza, garaza.",
        "price":        235000,
        "currency":     "EUR",
        "area_m2":      180,
        "city":         "Beograd",
        "municipality": "Zemun",
        "street":       "Gospodarska 7",
        "floor":        None,
        "total_floors": 2,
        "rooms":        5,
        "year_built":   2005,
        "heating":      "etazno",
        "parking":      True,
        "elevator":     False,
        "furnished":    "namesteno",
        "images":       ["https://placehold.co/800x600?text=Kuca+Zemun"],
        "active":       True,
    },
]
